---
- name: Get EC2 instances in this VPC
  amazon.aws.ec2_instance_info:
    filters:
      vpc-id: "{{ my_vpc.vpcs[0].vpc_id }}"
  register: ec2_info

- debug: var=ec2_info

- name: Terminating instances that were previously launched
  amazon.aws.ec2_instance:
    state: absent
    region: "{{ vpc.region }}"
    instance_ids: "{{ item.instance_id }}"
  with_items: "{{ ec2_info.instances }}"