---
# GENERAL
app_name: "abc"
aws_account_id: "XXXXXXXXXXXXXXXX"
aws_region: "us-east-1"
swarm_worker_node_count: 2

# VPC
aws_vpc_name: "{{app_name}}-app-vpc"
aws_vpc_cidr_block: 10.10.0.0/16
aws_subnet_name: "{{app_name}}-app-subnet"
aws_subnet_cidr_block: 10.10.1.0/24
aws_igw_name: "{{app_name}}-app-igw"
aws_route_table_name: "{{app_name}}-app-route-table"

# IAM
aws_iam_role_name: "{{app_name}}-app-ec2-to-ecr-access"

# Security Groups
aws_app_security_group_name: "{{app_name}}-ssl-http-https-sg"
aws_swarm_security_group_name: "{{app_name}}-docker-swarm-sg"
aws_ec2_outbound_to_rds_security_group_name: "{{app_name}}-ec2-outbound-to-rds"
aws_rds_inbound_from_ec2_app_security_group_name: "{{app_name}}-rds-inbound-from-ec2"

# EC2
aws_key_pair_name: "{{app_name}}-ec2-key-pair"
aws_key_pair_local_path: "~/.ssh/{{aws_key_pair_name}}.pem"
aws_ami: "ami-0a0e5d9c7acc336f1"
aws_default_instance_type: "t2.micro"
aws_ec2_security_groups:
  - "{{ aws_app_security_group_name }}"
  - "{{ aws_swarm_security_group_name }}"
aws_ec2_manager_tags:
  Name: "{{app_name}}-swarm-manager"
  Swarm: yes
  SwarmType: manager
aws_ec2_worker_tags:
  Name: "{{app_name}}-swarm-worker"
  Swarm: yes
  SwarmType: worker

ansible_user: "ubuntu"
ansible_private_key_file: "{{ aws_key_pair_local_path }}"

