---
- name: "Provision Docker Swarm workers EC2 instances."
  amazon.aws.ec2_instance:
    key_name: "{{ aws_key_pair_name }}"
    image_id: "{{ aws_ami }}"
    instance_type: "{{ aws_default_instance_type }}"
    vpc_subnet_id: "{{ my_subnet.subnet.id }}"
    iam_instance_profile: "{{ aws_iam_role_name }}"
    network:
      assign_public_ip: yes
    security_groups: "{{ aws_ec2_security_groups }}"
    tags: "{{ aws_ec2_worker_tags }}"
    wait: yes
    exact_count: "{{ swarm_worker_node_count }}"
  register: swarm_workers

# - name: Debug Swarm Workers. 
#   debug:
#     var: swarm_workers

- name: "Add Docker Swarm workers nodes to 'swarm_worker' inventory group."
  add_host:
    hostname: "{{ item.public_ip_address }}"
    groups:
      - swarm_worker
  with_items: "{{ swarm_workers.instances }}"