---
- name: "Create EC2 security group {{ aws_swarm_security_group_name }} for outbound traffic to RDS."
  amazon.aws.ec2_security_group:
    name: "{{ aws_ec2_outbound_to_rds_security_group_name }}"
    description: >-
      Allow outbound communication to the RDS (3306)
    state: present
    vpc_id: "{{ my_vpc.vpc.id }}"
    rules_egress:
      - proto: tcp
        from_port: 3306
        to_port: 3306
        group_name: "{{app_name}}-rds-ec2"
        group_desc: "Allow EC2 to RDS communication."
        rule_desc: "Outbound MYSQL traffic."
    tags:
      Name: "{{ aws_ec2_outbound_to_rds_security_group_name }}"

- name: "Create RDS security group {{ aws_rds_inbound_from_ec2_app_security_group_name }} for inbound traffic from EC2."
  amazon.aws.ec2_security_group:
    name: "{{ aws_rds_inbound_from_ec2_app_security_group_name }}"
    description: >-
      Allow outbound communication to the RDS (3306)
    state: present
    vpc_id: "{{ my_vpc.vpc.id }}"
    rules:
      - proto: tcp
        from_port: 3306
        to_port: 3306
        group_name: "{{app_name}}-rds-ec2"
        group_desc: "Allow EC2 to RDS communication."
        rule_desc: "Inbound MYSQL traffic from EC2."
    tags:
      Name: "{{ aws_rds_inbound_from_ec2_app_security_group_name }}"