---
- name: "Create EC2 security group {{ aws_app_security_group_name }} for Applications."
  amazon.aws.ec2_security_group:
    name: "{{ aws_app_security_group_name }}"
    description: >-
      Allow SSH connections.
      Allow HTTP connections.
      Allow HTTPS connections.
      Allow HTTP/8080 connections.
    state: present
    vpc_id: "{{ my_vpc.vpc.id }}"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        rule_desc: "Allow SSH from everywhere."
        cidr_ip: 0.0.0.0/0
        cidr_ipv6: ::/0
      - proto: tcp
        from_port: 80
        to_port: 80
        rule_desc: "Allow HTTP from everywhere."
        cidr_ip: 0.0.0.0/0
        cidr_ipv6: ::/0
      - proto: tcp
        from_port: 443
        to_port: 443
        rule_desc: "Allow HTTPS from everywhere."
        cidr_ip: 0.0.0.0/0
        cidr_ipv6: ::/0
      - proto: tcp
        from_port: 8080
        to_port: 8080
        rule_desc: "Open HTTP/8080 for Docker Swarm Visualizer."
        cidr_ip: 0.0.0.0/0
        cidr_ipv6: ::/0
    tags:
      Name: "{{ aws_app_security_group_name }}"