---
- name: "Deleting IAM Role Instance Profile."
  amazon.aws.iam_instance_profile:
    name: "{{ aws_iam_role_name }}"
    state: absent

- name: "Deleting IAM Role to allow EC2 access to ECR."
  amazon.aws.iam_role:
    name: "{{ aws_iam_role_name }}"
    assume_role_policy_document: "{{ lookup('file', '../../files/iam_role_policy.json') }}"
    description: Allow the EC2 instance to pull Docker images from ECR.
    managed_policies:
      - arn:aws:iam::aws:policy/service-role/AWSAppRunnerServicePolicyForECRAccess
    state: absent
  register: iam_role
#
#- debug: var=iam_role
