---
- name: "Deleting {{ aws_key_pair_name }} since it couldn't be saved."
  amazon.aws.ec2_key:
    name: "{{ aws_key_pair_name }}"
    state: absent

- name: "Deleting {{ aws_key_pair_local_path }} key pair file."
  ansible.builtin.file:
    path: "{{ aws_key_pair_local_path }}"
    state: absent