---
- name: Get a list of all security groups belonging to this VPC
  amazon.aws.ec2_security_group_info:
    filters:
      vpc-id: "{{ my_vpc.vpcs[0].vpc_id }}"
  register: sg_info

#- debug: var=sg_info

- name: Delete security groups in VPC
  amazon.aws.ec2_security_group:
    group_id: "{{ item.group_id }}"
    state: absent
  with_items: "{{ sg_info.security_groups }}"
  ignore_errors: yes