---
- hosts: swarm_manager[0]
  become: true
  vars_files:
    - ../../server/server_settings.yml

  tasks:
    - name: Create VPC and subnet
      include_tasks: "tasks/deploy_{{ cloud_provider }}.yml"
