---
- hosts: swarm_manager[0]
  become: true
  vars_files:
    - ../../server/server_settings.yml
    - ../../deploy_settings.yml

  tasks:
    - name: Create Docker credentials for ECR access.
      shell: "aws ecr get-login-password --region {{ ecr_aws_region }} | docker login --username AWS --password-stdin {{ ecr_aws_account_id }}.dkr.ecr.us-east-1.amazonaws.com"
      when: is_ecr_login_needed

#    - name: Pull image, start container, and run command
#      shell: |
#        docker run -it 781477923825.dkr.ecr.us-east-1.amazonaws.com/larademo:latest php artisan migrate
#
#
