---

# Create DNS records for the ALB
- name: Create DNS records for the new ALB
  amazon.aws.route53:
    state: present
    zone: "{{domain}}"
    record: "{{sub_domain}}"
    type: CNAME
    ttl: 300
    value: "{{my_alb.results[0].dns_name}}"
    overwrite: yes