---
- name: Tear down the swarm architecture
  hosts: localhost
  gather_facts: false
  become: true
  vars_files:
    - ../../../../server/swarm_settings.yml

  tasks:
    - name: "Query for existing vpc by name ({{ vpc.name }})"
      ec2_vpc_net_info:
        region: "{{ vpc.region }}"
        filters:
          "tag:Name": "{{ vpc.name }}"
      register: my_vpc

    - fail:
        msg: "No vpc could be located by the name {{ aws_vpc_name }}"
      when: my_vpc.vpcs | length == 0

    #    - debug: var=my_vpc

    - include_tasks: tasks/teardown/redis.yml
    - include_tasks: tasks/teardown/rds.yml
    - include_tasks: tasks/teardown/ec2.yml
    - include_tasks: tasks/teardown/key_pair.yml
    - include_tasks: tasks/teardown/security_groups.yml
    - include_tasks: tasks/teardown/swarm_node_iam_role.yml
    - include_tasks: tasks/teardown/alb.yml
    - include_tasks: tasks/teardown/network.yml

