version: "3"

services:
  mysql:
    #image: mariadb:${MARIADB_VERSION}
    image: mysql:${MYSQL_VERSION}
    ports:
      - "3306:3306"
    volumes:
      - /home/ubuntu/database/${COMPOSE_PROJECT_NAME}_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    deploy:
      placement:
        constraints: [ node.role == manager ]