---
- hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - ../../../settings.yml

  tasks:
    - name: Create VPC and subnet
      include_tasks: tasks/create/vpc.yml

    - name: Create AWS IAM role that allows EC2 to pull images from ECR
      include_tasks: tasks/create/iam_role.yml

    - name: Create AWS security group for the application.
      include_tasks: tasks/create/security_group_app.yml

    - name: Create AWS security group for Docker Swarm.
      include_tasks: tasks/create/security_group_swarm.yml

    #    - name: Create AWS security group for EC2 to RDS connections.
    #      include_tasks: tasks/create/security_group_ec2_to_rds.yml

    - name: Create AWS key pair used to create EC2 instances.
      include_tasks: tasks/create/key_pair.yml

    - name: Create Docker Swarm manager nodes.
      include_tasks: tasks/create/nodes_managers.yml

    - name: Create Docker Swarm worker nodes.
      include_tasks: tasks/create/nodes_workers.yml

#    - name: Dynamically create inventory file using template.
#      template: src=../../../inventories/inventory.j2 dest=../../../inventory
