---
- hosts: swarm_manager
  gather_facts: true
  vars_files:
    - ../settings.yml

  tasks:
    - name: Show the info
      debug:
        msg: "Manager node: {{ inventory_hostname }}"

- hosts: swarm_worker
  connection: local
  gather_facts: false
  vars_files:
    - ../settings.yml

  tasks:
    - name: Show the info
      debug:
        msg: "Worker node: {{ inventory_hostname }}"


- hosts: all
  connection: local
  gather_facts: false
  vars_files:
    - ../settings.yml

  tasks:
    - name: Show the info
      debug:
        msg: "Swarm node: {{ inventory_hostname }}"