---
- hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - ./../server/swarm_settings.yml

  tasks:

    - name: Create ALB
      include_tasks: "provisioners/aws/swarm/tasks/create/dns_host.yml"


